- src/App.js
- src/api/network.js
- src/components/layout/Footer.js
- src/components/layout/Sidebar.js
- src/components/layout/index.js
- src/components/modals/ConfirmEmail.js
- src/components/modals/SessionExpired.js
- src/components/modals/wallet/UnlockWalletModal.js
- src/components/styled.js
- src/pages/login/index.js
- src/providers/Authorization.js
- src/providers/syncLoginState.js
- src/redux/actions.js
- src/redux/auth.js
- src/redux/index.js
- src/redux/session.js
- src/redux/wallet.js
Sync login state between tabs.
> [ONXP-351] Session implementation

- src/api/assets.js
- src/pages/send-asset/index.js
- src/utils/number.js
Fixes bugs in Firefox.
Includes fee calculation.
> Bugfix for SendAssets

- package-lock.json
- src/api/assets.js
- src/api/constants.js
- src/assets/styles/_send-assets.scss
- src/assets/styles/index.scss
- src/components/notification.js
- src/pages/send-asset/index.js
- src/utils/blockchain.js
Problem with validation amount after send some assents
https://scaddr.apriorit.com/jira/browse/ONXP-749
Isn't displayed increase/decrease component on mob browsers
https://scaddr.apriorit.com/jira/browse/ONXP-751
Add information about a compensation commission per transaction
https://scaddr.apriorit.com/jira/browse/ONXP-691
Need to fix increase component
https://scaddr.apriorit.com/jira/browse/ONXP-745
Also improved styles for mobile devises.
> Send bug fix

- src/pages/admin-panel/requests/UserUpgradeRequests.js
[ONXP-773](https://scaddr.apriorit.com/jira/browse/ONXP-773) [Account Upgrade] Need to delete the button "Downgrade" when user is customer: added disabling 'Downgrade' button, if current user role is 'client'.
> Added disabling 'Downgrade' button, if current user role is 'client'

- src/pages/requests/ActiveRequests.js
- src/pages/requests/ClosedRequests.js
All requests created by other users are displayed on Requests pages
https://scaddr.apriorit.com/jira/browse/ONXP-766
> [ONXP-766] add aditional param of requests API call

- src/components/modals/SendToAgent/index.js
- src/pages/requests/table-columns/renderAgentColumns.js
- src/pages/send-asset/index.js
oUSD asset is always displayed as default on Send page
https://scaddr.apriorit.com/jira/browse/ONXP-774
"Perform" button is displayed for complained request on agent's page
https://scaddr.apriorit.com/jira/browse/ONXP-789
Timer is displayed for complained request on agent's page
https://scaddr.apriorit.com/jira/browse/ONXP-787
> Deposit bugfix

- src/api/constants.js
- src/components/balance/Balance.js
- src/pages/login/index.js
- src/providers/balanceProvider.js
Refactor of BalanceProvider:
- convert API calls from sequential to parallel; 
- fetch only necessary balances for each user role
- don't fetch balances, when the user is not logged in
- don't fetch balances for users with Admin roles
Fix bug in BalnceCard for super_agents.
> Refactor balance provider

- package-lock.json
- package.json
- src/components/modals/Registration.js
- src/pages/login/index.js
[ONXP-842](https://scaddr.apriorit.com/jira/browse/ONXP-842) [Sprint 5] Referal link support:
User follows link with referral code, f.e.: 
http://localhost:3000/login?rcode=ARgUc5RC7yZpNe6RAWK6EzTwcKA8uu3r2b
rcode from the link is saved in localstorage and will be automatically inserted in signup form.
> saving referral wallet in localstorage

- src/pages/send-asset/index.js
[ONXP-805](https://scaddr.apriorit.com/jira/browse/ONXP-805) [Send] Saved postal addresses are offered for entry in "address" input field: 
Disabled autocomplete for address input field.
> Onxp 805 saved postal addresses are offered for entry in address input field

- package-lock.json
- src/components/modals/Registration.js
- src/pages/send-asset/index.js
[ONXP-803](https://scaddr.apriorit.com/jira/browse/ONXP-803) [Send] Message about insufficient amount of assets must be displayed on send page:
- if user has no assets on account, corresponding error message appears 
- discovered and fixed error with signup validation:  edited signup modal validation, now referral code is not not required to sign up
> Onxp 803 message about insufficient amount of assets must be displayed on send page

- src/pages/admin-panel/users/index.js
ONXP-827 [Gideon][Users mng][UI] Actions column must be moved to the left edge:
Moved column with actions to right edge of the table.
> Moved column with actions to right edge of the table.

- src/pages/profile/ReferralLink.js
**[ONXP-896 [Profile] Incorrect referral link is displayed in profile](https://scaddr.apriorit.com/jira/browse/ONXP-896)**
- fixed format of referral link in profile
> ONXP-896 Incorrect referral link is displayed in profile

- src/pages/admin-panel/requests/UserUpgradeRequests.js
- Added displaying user role at the moment of request creation instead of current user role 
- Displaying request creation time
> Onxp 798 creation time of upgrade request must be displayed on admin panel

- src/pages/admin-panel/requests/UserUpgradeRequests.js
- changed request status names 
- checked, that upgrading works fine, completed status is successfully set
> Onxp 800 confirmed upgrade request must be filtered as accepted

- src/pages/admin-panel/requests/UserUpgradeRequests.js
limited table height, to vertical scroll always appears on the page.
> limited table y scroll width

- src/pages/send-asset/index.js
trying to fix autocomplete issue for mobile devices: changed autocomplete to autoComplete
> ONXP-805 [Send] Saved postal addresses are offered for entry in "address" input field

- src/pages/dashboard.js
rendering transactions table only if user status is active
> rendering transactions table only if user status is active

- src/pages/admin-panel/users/index.js
ONXP-1055 [Admin Panel][Users] Search in columns does not work at all +     ONXP-1056 [Admin Panel][Users] Add sorting functionality into the columns:
- stabilized sorting
- implemented filtering with radio-buttons for role and status
- fixed issue with infinite spinner if error occurred when fetching data
- implemented UI for server-side sorting of firstName and lastName (both asc and desc)
> Search in admin panel user list

- src/assets/styles/_profile.scss
- src/pages/profile/DeleteAccount.js
- src/pages/profile/ProfileEditor.js
- src/pages/profile/ReferralLink.js
- src/pages/referral-program/index.js
ONXP-1233 [User profile] Rename Delete my user account button and make it inactive
ONXP-1231 [User profile] Improve Change email pop-up texting
ONXP-1229 [User profile] Improve text in Change phone number pop-up
ONXP-1228 [User profile] Text explanation has to be provided under Referral information section
ONXP-1227 [User profile] "Referral info" has to be replaced with "Referral information"
> Profile and referral information improvements

- src/pages/admin-panel/requests/ComplaintsList.js
- src/pages/admin-panel/users/index.js
> ONXP-1185_Complaints_mng_Notification_is_not_displayed_on_web-page_when_complaint_is_resolved

- src/pages/profile/ReferralLink.js
ONXP-1228 [User profile] Text explanation has to be provided under Referral information section:
- updated referral link explanation text.
> ONXP-1228 [User profile] Text explanation has to be provided under Referral information section:

- src/pages/admin-panel/users/index.js
ONXP-1206 [Admin Panel][Users] Add possibility of multiple filtering for role and status columns:
- added multiple filtering for status and role columns
> added multiple filtering for status and role columns

- src/pages/admin-panel/requests/ResolvedComplaints.js
ONXP-1339 [Complaints mng] "Made a decision" column must be hidden for resolved complaints:
- deleted "Made a decision" column
> ONXP-1339 [Complaints mng] "Made a decision" column must be hidden for resolved complaints

- src/pages/admin-panel/users/userDetailedData.js
- src/utils/index.js
- fixed displaying of admin role in users list
- not able to block user whose role code is bigger than your own
> Onxp 1335 ability to block admin accounts should be disabled for support

- src/components/paginated-list/OperationsWidget.js
- src/pages/dashboard.js
ONXP-1383 - [Transactions list] "Reward" column should be added for Agents and Super agents
ONXP-1382 - [Transactions list] "Fee" column should not be displayed for Agents and Super agents
> Trx list on Dashboard

- src/providers/balanceProvider.js
> ONXP-1391 [Login] Uncaught exception when you have not logged in wallet

- src/pages/requests/table/columns/renderPerformerColumns.js
Changed the caption on the cancel button
> ONXP-1369 [Withdraw][GUI] "Cancel" button is displayed for confirmed request instead of "Cancel confirmation"

- src/components/modals/ChoosePerformer/index.js
Changed request sending message
> ONXP-1401 [Gideon][GUI] Change message which appears after request creation

- src/components/notification.js
Changed the notification display time to infinity
> ONXP-1399 [Gideon][GUI] Pop- up messages should not disappear - they should stay on the screen until the user cancels (close) it

- src/pages/requests/table/columns/renderInitiatorColumns.js
Renamed "Choose agent" button caption to “Confirm agent"
> ONXP-1398 [Gideon][Deposit][Withdraw] Rename "Choose agent" to “Confirm agent" on the client side

- src/api/constants.js
- src/pages/upgrade-user/index.js
Changed text and fee for upgrading to Agent.
> ONXP-1440 - [Gideon][BlockChain] Agent should pay 800$ instead of 500$ and get 500 OnyxCash

- src/components/balance/RewardsBalance.js
- src/components/notification.js
- src/pages/send-asset/index.js
- src/utils/blockchain.js
Changed Blockchain error to Invalid address error
> ONXP-1381 [Send] Blockchain error is displayed when several spaces are entered as address

- src/components/balance/RewardsBalance.js
- src/pages/referral-program/ReferralReward.js
Changed "received rewards" to "commission earned"
> ONXP-1430 [Gideon][Rewards] Change Total received rewards to Total commission earned

- src/pages/assets-exchange/index.js
Changed the table adaptability
> ONXP-1354 [Exchange][Edge][GUI] A scroll is displayed in thet table with balances on Exchange page, if there are a lot free space for it

- src/components/modals/ChoosePerformer/index.js
Changed the message text.
Now clients are getting old version of message
and agents are getting new one
> ONXP-1428 [Deposit][GUI] Change message which appears after deposit onyxcash request creation

- src/components/modals/ChoosePerformer/index.js
> ONXP-1428 Change message which appears after deposit onyxcash request creation

- src/api/operation-messages.js
> ONXP-1338 Message is sent to potential performer without wallet address

- src/api/admin/assets.js
- src/api/admin/complaints.js
- src/api/admin/user-upgrade.js
- src/api/admin/users.js
- src/api/assets.js
- src/api/dev-options.js
- src/api/exchange.js
- src/api/requests.js
- src/api/wallet.js
- src/components/balance/Balance.js
- src/components/layout/UserWalletAddress.js
- src/components/modals/Registration.js
- src/pages/login/index.js
- src/providers/balanceProvider.js
- src/redux/admin-panel/investment.js
- Fixed incorrect account passed into transactions
- Fixed deposit balance display
> ONXP-1500 - Bugfix

- src/api/constants.js
changed amount to pay for becoming superagent
>     ONXP-1579  [Gideon][Upgrade] Change message on "Upgrade to the Super agent" page

- src/api/constants.js
- src/pages/admin-panel/requests/UserUpgradeRequests.js
https://scaddr.apriorit.com/jira/browse/ONXP-1617
> I changed rates for agents and super agents 

- src/api/constants.js
https://scaddr.apriorit.com/jira/browse/ONXP-1630
> I changed rates for superagent

- src/pages/upgrade-user/CoinPaymentsForm.js
Changed a coinpayments form method to open the right link in the mobile app.
> ONXP-1541 Wrong coinpayments link

- src/components/modals/wallet/CreateWalletModal.js
- src/pages/wallet-setting/index.js
Changes to download a wallet file in mobile app
> ONXP-1530 Crashing of application when downloading wallet

- src/components/layout/Footer.js
- src/pages/profile/ProfileEditor.js
- src/pages/upgrade-user/CoinPaymentsForm.js
Made some external links open in the browser on Android
Associated PR on Android: https://github.com/OnyxPay/android-app/pull/11
> ONXP-1562 All external links must be opened in the browser instead of application

- src/components/layout/Footer.js
- src/components/modals/wallet/CreateWalletModal.js
- src/pages/profile/ProfileEditor.js
- src/pages/upgrade-user/CoinPaymentsForm.js
- src/pages/wallet-setting/index.js
Change Android to AndroidWebview
> ONXP-1822 [Mob_App] List of features don't work when preprod opened in the mobile browser
